databases:
  - name: gameaward-production
    databaseName: gameaward_production_fl5q
    user: mana
    region: singapore

services:
  - type: web
    name: gameaward
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gameaward-production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false